import { NextRequest, NextResponse } from 'next/server';
import { auth, clerkClient } from '@clerk/nextjs/server';

export async function POST(req: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    const { blueprintMarkdown } = body;

    const client = await clerkClient();
    const { data } = await client.users.getUserOauthAccessToken(userId, 'oauth_github');
    const githubToken = data[0]?.token;

    if (!githubToken) {
      return NextResponse.json({ error: 'GitHub account not linked.' }, { status: 400 });
    }

    const randomStr = Math.random().toString(36).substring(2, 8);
    const repoName = `BlueprintAI-Generated-App-${randomStr}`;

    const createRepoRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${githubToken}`,
        'Content-Type': 'application/json',
        'Accept': 'application/vnd.github.v3+json'
      },
      body: JSON.stringify({
        name: repoName,
        private: true,
        auto_init: false
      })
    });

    if (!createRepoRes.ok) {
      const errorText = await createRepoRes.text();
      return NextResponse.json({ error: `GitHub API Error: ${errorText}` }, { status: 500 });
    }

    const repoResponseData = await createRepoRes.json();
    const owner = repoResponseData.owner.login;
    const repo = repoResponseData.name;

    const commitFile = async (path: string, content: string, message: string) => {
      const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
        method: 'PUT',
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Content-Type': 'application/json',
          'Accept': 'application/vnd.github.v3+json'
        },
        body: JSON.stringify({
          message,
          content: Buffer.from(content).toString('base64')
        })
      });
      if (!res.ok) {
        const errorText = await res.text();
        throw new Error(`Failed to commit ${path}: ${errorText}`);
      }
    };

    let clinerulesContent = '';
    const clinerulesMatch = blueprintMarkdown?.match(/```(?:clinerules|markdown)?\n([\s\S]*?)```/g);
    if (clinerulesMatch) {
      for (const block of clinerulesMatch) {
        if (block.includes('clinerules') || block.includes('RULES:')) {
          clinerulesContent = block.replace(/```.*?\n/, '').replace(/```$/, '');
          break;
        }
      }
    }

    // Default README
    await commitFile('README.md', blueprintMarkdown || '# Generated by BlueprintAI', 'Initial commit: README');

    if (clinerulesContent) {
      await commitFile('.clinerules', clinerulesContent, 'Initial commit: .clinerules');
    }

    return NextResponse.json({ repoUrl: repoResponseData.html_url });
  } catch (error: any) {
    console.error('API Error:', error);
    return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
  }
}
