import { NextRequest, NextResponse } from 'next/server';
import { auth, clerkClient } from '@clerk/nextjs/server';

export async function POST(req: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { appName, clinerules, schema } = await req.json();

    if (!appName) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const client = await clerkClient();
    console.log("Attempting to fetch GitHub token for user:", userId);
    const { data } = await client.users.getUserOauthAccessToken(userId, 'oauth_github');
    const token = data[0]?.token;

    if (!token) {
      console.error("❌ Failed to retrieve GitHub token. Did the user link their account?");
      return NextResponse.json({ error: 'GitHub account not linked. Please connect your GitHub account.' }, { status: 401 });
    }
    
    console.log("✅ GitHub Token retrieved successfully!");

    const sanitizedName = appName.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '') || 'blueprint-app';

    // Step 1: Create Repo
    const createRepoRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: sanitizedName,
        private: true,
        description: 'Generated by BlueprintAI',
        auto_init: true, // initializes with a README
      }),
    });

    if (!createRepoRes.ok) {
      const errorData = await createRepoRes.json();
      return NextResponse.json({ error: 'Failed to create repo', details: errorData }, { status: createRepoRes.status });
    }

    const repoData = await createRepoRes.json();
    const owner = repoData.owner.login;
    const repo = repoData.name;
    const repoUrl = repoData.html_url;

    const createOrUpdateFile = async (path: string, content: string, message: string) => {
      // Get the SHA if it exists (e.g. README.md created by auto_init)
      let sha: string | undefined;
      const getFileRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Accept': 'application/vnd.github.v3+json',
        },
      });
      if (getFileRes.ok) {
        const fileData = await getFileRes.json();
        sha = fileData.sha;
      }

      const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
        method: 'PUT',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          message,
          content: Buffer.from(content).toString('base64'),
          sha,
        }),
      });
      if (!res.ok) {
        throw new Error(`Failed to create ${path}`);
      }
    };

    // Step 2: Create/Update README
    const readmeContent = `# ${appName}\n\n![Generated by BlueprintAI](https://img.shields.io/badge/Generated%20by-BlueprintAI-06b6d4?style=for-the-badge)\n\nThis architecture and foundation was automatically generated by BlueprintAI.`;
    await createOrUpdateFile('README.md', readmeContent, 'docs: Update README.md');

    // Step 3: Create .clinerules
    if (clinerules) {
      await createOrUpdateFile('.clinerules', clinerules, 'build: Inject .clinerules A2A config');
    }

    // Step 4: Create schema.sql
    if (schema) {
      await createOrUpdateFile('schema.sql', schema, 'db: Inject schema.sql');
    }

    return NextResponse.json({ success: true, url: repoUrl });
  } catch (error: any) {
    console.error('GitHub Init Error:', error);
    return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
  }
}
